import type { FormEvent } from 'react';
import { AlertTriangle, Award, CheckCircle2, Fingerprint, KeyRound, Lock, Mail } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { AdvocateLoginFields } from '@/types/authForms';

interface AdvocateLoginFormProps { fields: AdvocateLoginFields; showSuccess: boolean; showRecovery: boolean; submitting: boolean; onShowRecovery: () => void; onChange: <K extends keyof AdvocateLoginFields>(key: K, value: AdvocateLoginFields[K]) => void; onSubmit: (event: FormEvent) => void }

export function AdvocateLoginForm(props: AdvocateLoginFormProps) {
  return (
    <>
      {props.showSuccess && <div role="status" className="p-4 rounded-2xl bg-emerald-500/15 border border-emerald-500/40 flex items-start gap-3 text-xs"><CheckCircle2 className="w-5 h-5 text-emerald-500" /><p className="font-semibold text-emerald-600 dark:text-emerald-300">Verifikasi KYC &amp; sinkronisasi SIPP Mahkamah Agung berhasil! Silakan masuk dengan kredensial KMS Anda.</p></div>}
      <form onSubmit={props.onSubmit} className="space-y-4 animate-fade-in">
        <label className="space-y-1.5 text-xs font-semibold text-foreground">Nomor Induk Advokat (NIA / SIPP)<div className="relative flex items-center"><Award className="absolute left-3.5 w-5 h-5 text-emerald-400" /><Input value={props.fields.nia} onChange={(event) => props.onChange('nia', event.target.value)} placeholder="18293/PERADI/2015" required style={{ paddingLeft: '3.25rem' }} className="w-full pr-4 h-12 rounded-xl bg-secondary border-border font-mono" /></div></label>
        <label className="space-y-1.5 text-xs font-semibold text-foreground">Alamat Email Profesional<div className="relative flex items-center"><Mail className="absolute left-3.5 w-5 h-5 text-muted-foreground" /><Input type="email" value={props.fields.email} onChange={(event) => props.onChange('email', event.target.value)} placeholder="mahendra.k@lawfirm.id" required style={{ paddingLeft: '3.25rem' }} className="w-full pr-4 h-12 rounded-xl bg-secondary border-border" /></div></label>
        <div className="space-y-1.5"><div className="flex justify-between items-center"><label className="text-xs font-semibold text-foreground">Kata Sandi Keamanan KMS</label><button type="button" onClick={props.onShowRecovery} className="text-xs text-emerald-400 hover:text-emerald-300 font-medium">Lupa PIN KMS / Kredensial?</button></div><div className="relative flex items-center"><KeyRound className="absolute left-3.5 w-5 h-5 text-muted-foreground" /><Input type="password" value={props.fields.kmsPassword} onChange={(event) => props.onChange('kmsPassword', event.target.value)} placeholder="••••••••••••••••••••••••" required style={{ paddingLeft: '3.25rem' }} className="w-full pr-4 h-12 rounded-xl bg-secondary border-border font-mono" /></div></div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1 border-t border-border"><label className="space-y-1.5 text-xs font-semibold text-foreground"><span className="flex items-center gap-1.5"><Fingerprint className="w-3.5 h-3.5 text-emerald-400" />Kode MFA (6-Digit OTP)</span><Input value={props.fields.mfaOtp} onChange={(event) => props.onChange('mfaOtp', event.target.value)} placeholder="4  8  1  9  0  2" maxLength={6} required className="w-full h-11 rounded-xl bg-background border-border text-emerald-400 font-mono text-center" /></label><label className="space-y-1.5 text-xs font-semibold text-foreground"><span className="flex items-center gap-1.5"><Lock className="w-3.5 h-3.5 text-blue-400" />PIN e-Meterai KMS</span><Input type="password" value={props.fields.kmsPin} onChange={(event) => props.onChange('kmsPin', event.target.value)} placeholder="••••••" maxLength={6} required className="w-full h-11 rounded-xl bg-background border-border font-mono text-center" /></label></div>
        <label className="p-3.5 rounded-xl bg-emerald-500/15 border border-emerald-500/30 flex items-start gap-3 text-xs"><input type="checkbox" checked={props.fields.hardwareBoundSession} onChange={(event) => props.onChange('hardwareBoundSession', event.target.checked)} required className="rounded mt-0.5 w-4 h-4" /><span><strong className="block text-foreground">Sesi Kerja Enkripsi E2EE Terproteksi</strong><span className="text-[11px] text-emerald-400">Hardware-bound Session Token • FIDO2 WebAuthn &amp; Mutex Locking Ready</span></span></label>
        <Button type="submit" size="lg" disabled={props.submitting} className="w-full h-12 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 text-white font-bold text-sm shadow-xl gap-2"><CheckCircle2 className="w-5 h-5" />{props.submitting ? 'MEMVERIFIKASI SESI...' : 'MASUK KE COMMAND CENTER ADVOKAT'}</Button>
      </form>
      {props.showRecovery && <div className="p-3.5 rounded-2xl bg-blue-500/15 border border-blue-500/40 flex items-start gap-3 text-xs text-blue-300"><AlertTriangle className="w-5 h-5 text-blue-400" /><div><p className="font-bold text-foreground uppercase text-[11px]">PEMULIHAN KREDENSIAL KMS:</p><p className="text-muted-foreground mt-0.5">Untuk memulihkan PIN e-Meterai Peruri atau token FIDO2, hubungi tim keamanan siber Mahkamah Agung &amp; Peruri atau gunakan kunci pemulihan HSM fisik Anda.</p></div></div>}
    </>
  );
}
